// Package codegen generates Go source code from the gsx
// intermediate representation.
package codegen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/xDarkicex/nanite-gsx/internal/ir"
	"github.com/xDarkicex/nanite-gsx/internal/parser"
)

// Generate produces the complete .go output for a parsed .gsx
// file: imports, the strongly-typed render function (internal
// fast path), and the Engine registration wrapper (external
// dynamic path via render.Engine).
func Generate(p *parser.ParsedFile) (string, error) {
	g := &generator{buf: new(bytes.Buffer), parsed: p}
	g.emitHeader()
	if _, err := g.walk(0, p.Body.Count); err != nil {
		return "", err
	}
	g.emitFooter()
	return g.buf.String(), nil
}

type generator struct {
	buf    *bytes.Buffer
	parsed *parser.ParsedFile
	indent int
}

func (g *generator) emitHeader() {
	p := g.parsed
	g.line("// Code generated by nanite-gsx. DO NOT EDIT.")
	g.line("")

	// Package declaration from the .gsx file's package (default "views").
	pkg := "views"
	g.linef("package %s", pkg)
	g.line("")

	// Imports.
	g.line("import (")
	g.line(`"fmt"`)
	g.line(`"html"`)
	for _, imp := range p.Imports {
		switch {
		case imp.Alias != "" && len(imp.Symbols) == 0:
			g.linef(`%s %q`, imp.Alias, imp.Path)
		case len(imp.Symbols) > 0:
			g.linef(`%s %q`, g.genPkgAlias(imp), imp.Path)
		default:
			g.linef(`_ %q`, imp.Path)
		}
	}
	if p.PropsType != "" {
		// Props type is defined in the same package.
	}
	if p.HasComponents {
		g.line("")
		g.line(`"github.com/xDarkicex/nanite-gsx"`)
		g.line(`"github.com/xDarkicex/nanite-render"`)
	}
	g.line(")")
	g.line("")

	// Props type alias (for destructured imports).
	if len(p.Imports) > 0 {
		for _, imp := range p.Imports {
			if len(imp.Symbols) > 0 {
				alias := g.genPkgAlias(imp)
				for _, sym := range imp.Symbols {
					g.linef("type %s = %s.%s", sym, alias, sym)
				}
			}
		}
	}

	// The strongly-typed render function.
	params := append([]string{"c *render.ComponentContext"}, p.Params...)
	returns := "error"
	g.line("")
	g.linef("func Render%s(%s) %s {", p.FuncName, strings.Join(params, ", "), returns)
	g.indent = 1
}

func (g *generator) emitFooter() {
	p := g.parsed
	g.indent = 0
	g.line("}")
	g.line("")

	// The registration wrapper (external dynamic path).
	regName := "Register" + p.FuncName
	g.linef("func %s(e *gsx.Engine) {", regName)
	g.indent = 1
	g.linef(`e.Register(%q, func(c *render.ComponentContext, data any) error {`, p.FuncName)

	// Bridge: dynamic any → typed props.
	if p.PropsType != "" {
		g.linef("props := data.(%s)", p.PropsType)
		g.linef("return Render%s(c, props)", p.FuncName)
	} else if len(p.Params) == 0 {
		g.linef("return Render%s(c)", p.FuncName)
	} else {
		g.linef("return Render%s(c, data)", p.FuncName)
	}

	g.indent = 1
	g.line("})")
	g.indent = 0
	g.line("}")
}

func (g *generator) walk(start, end int) (int, error) {
	total := 0
	for i := start; i < end; i++ {
		consumed, err := g.emitNode(i)
		if err != nil {
			return 0, err
		}
		total += consumed
		i += consumed - 1
	}
	return total, nil
}

func (g *generator) emitNode(i int) (int, error) {
	s := g.parsed.Body

	switch s.Kind[i] {
	case ir.KindText:
		if t := s.Text[i]; t != "" {
			g.linef("c.WriteString(`%s`)", t)
		}

	case ir.KindExpr:
		g.linef("c.WriteString(html.EscapeString(fmt.Sprint(%s)))", s.Text[i])

	case ir.KindRawExpr:
		g.linef("c.WriteString(fmt.Sprint(%s))", s.Text[i])

	case ir.KindHTMLTag:
		g.emitOpenTag(i)
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		return consumed, nil

	case ir.KindHTMLClose:
		g.linef("c.WriteString(`</%s>`)", s.Tag[i])

	case ir.KindComponent:
		g.emitComponent(i)

	case ir.KindIf:
		return g.emitIf(i)

	case ir.KindFor:
		g.linef("for %s {", s.Cond[i])
		g.indent++
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		g.line("}")
		return consumed, nil

	case ir.KindSwitch:
		g.linef("switch %s {", s.Cond[i])
		g.indent++
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		g.line("}")
		return consumed, nil

	case ir.KindCase:
		g.linef("case %s:", s.Cond[i])
		g.indent++
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		return consumed, nil

	case ir.KindDefault:
		g.line("default:")
		g.indent++
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		return consumed, nil
	}
	return 1, nil
}

func (g *generator) emitIf(i int) (int, error) {
	s := g.parsed.Body
	g.linef("if %s {", s.Cond[i])
	g.indent++
	consumed := 1
	fc := int(s.FirstChild[i])
	if fc != -1 {
		n, err := g.walk(fc, g.siblingEnd(fc))
		if err != nil {
			return 0, err
		}
		consumed += n
	}
	g.indent--
	ns := int(s.NextSibling[i])
	if ns != -1 && s.Kind[ns] == ir.KindElse {
		g.line("} else {")
		g.indent++
		efc := int(s.FirstChild[ns])
		if efc != -1 {
			n, err := g.walk(efc, g.siblingEnd(efc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		consumed++
	}
	g.line("}")
	return consumed, nil
}

func (g *generator) emitOpenTag(i int) {
	s := g.parsed.Body
	tag := s.Tag[i]
	start := int(s.AttrStart[i])
	end := int(s.AttrEnd[i])
	if start == end {
		g.linef("c.WriteString(`<%s>`)", tag)
		return
	}
	var parts []string
	parts = append(parts, fmt.Sprintf("<%s", tag))
	for k := start; k < end; k++ {
		parts = append(parts, fmt.Sprintf(` %s="%s"`, s.AttrKeys[k], s.AttrVals[k]))
	}
	parts = append(parts, ">")
	g.linef("c.WriteString(`%s`)", strings.Join(parts, ""))
}

func (g *generator) emitComponent(i int) {
	s := g.parsed.Body
	name := s.Tag[i]
	start := int(s.AttrStart[i])
	end := int(s.AttrEnd[i])
	// Component call: RenderUserCard(c, props...)
	// The first arg is always c *render.ComponentContext.
	var args []string
	for k := start; k < end; k++ {
		args = append(args, g.genCompArg(s.AttrKeys[k], s.AttrVals[k]))
	}
	call := fmt.Sprintf("if err := Render%s(c", name)
	if len(args) > 0 {
		call += ", " + strings.Join(args, ", ")
	}
	call += "); err != nil { return err }"
	g.line(call)
}

func (g *generator) genPkgAlias(imp parser.Import) string {
	if imp.Alias != "" {
		return imp.Alias
	}
	// Generate alias from path: "myapp/models" -> "models"
	path := imp.Path
	if idx := strings.LastIndexByte(path, '/'); idx >= 0 {
		return path[idx+1:]
	}
	return path
}

// genCompArg formats a component attribute as a Go function argument.
// Keys are ignored in positional-style — all values are passed positionally.
func (g *generator) genCompArg(_, val string) string {
	return val
}

func (g *generator) siblingEnd(start int) int {
	s := g.parsed.Body
	cur := start
	for s.NextSibling[cur] != -1 {
		cur = int(s.NextSibling[cur])
	}
	return cur + 1
}

func (g *generator) line(s string) {
	for j := 0; j < g.indent; j++ {
		g.buf.WriteByte('\t')
	}
	g.buf.WriteString(s)
	g.buf.WriteByte('\n')
}

func (g *generator) linef(format string, args ...any) {
	g.line(fmt.Sprintf(format, args...))
}
