// Package codegen generates Go source code from the gsx
// intermediate representation.
package codegen

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/xDarkicex/nanite-gsx/internal/ir"
	"github.com/xDarkicex/nanite-gsx/internal/parser"
)

// Generate produces the complete .go output for a single parsed
// .gsx func: imports, the strongly-typed render function
// (internal fast path), and the Engine registration wrapper
// (external dynamic path via render.Engine).
func Generate(p *parser.ParsedFile) (string, error) {
	return GenerateFile([]*parser.ParsedFile{p})
}

// GenerateFile produces the .go output for a whole .gsx file
// (possibly multiple funcs, e.g. a component + its fallback).
// The first func's imports apply to the file.
func GenerateFile(files []*parser.ParsedFile) (string, error) {
	if len(files) == 0 {
		return "", nil
	}
	main := files[0]
	g := &generator{buf: new(bytes.Buffer)}
	g.parsed = main
	g.symbols = buildSymbols(main)
	g.emitHeader()
	// The stream starts with a synthetic document root (index 0) —
	// walk its children (the top-level nodes) via the sibling chain.
	fc := int(main.Body.FirstChild[0])
	if fc != -1 {
		if _, err := g.walk(fc, g.siblingEnd(fc)); err != nil {
			return "", err
		}
	}
	g.indent = 0
	g.line("return nil")
	g.emitFooter()

	// Additional funcs (fallbacks etc.) — each with its own
	// render + registration.
	for _, f := range files[1:] {
		g.parsed = f
		g.line("")
		g.line("")
		// Zero-byte marker type for cross-package imports.
		g.linef("type %s struct{}", f.FuncName)
		g.line("")

		// Multi-param additional funcs get their own props struct.
		if len(f.Params) > 1 {
			g.linef("type %sProps struct {", f.FuncName)
			g.indent++
			for _, param := range f.Params {
				fields := strings.Fields(param)
				if len(fields) < 2 {
					continue
				}
				name := fields[0]
				typ := fields[len(fields)-1]
				exported := strings.ToUpper(name[:1]) + name[1:]
				g.linef("%s %s `nanite:%q`", exported, typ, name)
			}
			g.indent--
			g.line("}")
			g.line("")
		}
		params := append([]string{"c *render.ComponentContext"}, f.Params...)
		params = append(params, "children func(c *render.ComponentContext) error")
		g.linef("func Render%s(%s) error {", f.FuncName, strings.Join(params, ", "))
		g.indent = 1
		fc := int(f.Body.FirstChild[0])
		if fc != -1 {
			if _, err := g.walk(fc, g.siblingEnd(fc)); err != nil {
				return "", err
			}
		}
		g.indent = 0
		g.line("return nil")
		g.emitFooter()
	}
	return g.buf.String(), nil
}

type generator struct {
	buf    *bytes.Buffer
	parsed *parser.ParsedFile
	indent int
	// symbols maps imported component tags to their package
	// alias: "Button" → "ui" means <Button/> resolves to
	// ui.RenderButton. Built from @import { X } from "..." —
	// the TSX-style cross-package composition mechanism.
	symbols map[string]string
}

// importsPath reports whether the .gsx file already imports path.
func importsPath(p *parser.ParsedFile, path string) bool {
	for _, imp := range p.Imports {
		if imp.Path == path {
			return true
		}
	}
	return false
}

// goStr escapes s for embedding in a double-quoted Go string
// literal. Static attribute values may contain quotes, which would
// otherwise break the generated code.
func goStr(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return s
}

// bodyHasExprs reports whether the body contains Go expressions
// ({expr}, dynamic attributes) that need the fmt/html imports.
func bodyHasExprs(p *parser.ParsedFile) bool {
	s := p.Body
	for i := 0; i < s.Count; i++ {
		if s.Kind[i] == ir.KindExpr || s.Kind[i] == ir.KindRawExpr || s.Kind[i] == ir.KindError {
			return true
		}
		for k := int(s.AttrStart[i]); k < int(s.AttrEnd[i]); k++ {
			if k < len(s.AttrDynamic) && s.AttrDynamic[k] {
				// x-data/x-init auto-hydrate via WriteHydrateProps —
				// no fmt/html needed.
				if s.AttrKeys[k] == "x-data" || s.AttrKeys[k] == "x-init" {
					continue
				}
				return true
			}
			if k < len(s.AttrSpread) && s.AttrSpread[k] {
				return true
			}
		}
	}
	return false
}

// buildSymbols maps destructured import symbols to their package
// alias. <Button/> in the template resolves to ui.RenderButton
// when Button was imported via @import { Button } from
// "myapp/components/ui".
func buildSymbols(p *parser.ParsedFile) map[string]string {
	m := make(map[string]string)
	for _, imp := range p.Imports {
		if len(imp.Symbols) == 0 {
			continue
		}
		alias := genPkgAlias(imp)
		for _, sym := range imp.Symbols {
			m[sym] = alias
		}
	}
	return m
}

func (g *generator) emitHeader() {
	p := g.parsed
	g.line("// Code generated by nanite-gsx. DO NOT EDIT.")
	g.line("")

	// Package declaration from the .gsx file's package (default "views").
	pkg := "views"
	g.linef("package %s", pkg)
	g.line("")

	// Imports. fmt/html are only needed when the body contains
	// {expressions} (escaping) — a static-only component skips them
	// so `go build` doesn't fail with "imported and not used".
	g.line("import (")
	hasExprs := bodyHasExprs(p)
	if hasExprs {
		// Skip auto fmt/html when the .gsx file imported them
		// explicitly (e.g. for @action/@memo bodies) — a
		// duplicate import would fail go build.
		if !importsPath(p, "fmt") {
			g.line(`"fmt"`)
		}
		if !importsPath(p, "html") {
			g.line(`"html"`)
		}
	}
	for _, imp := range p.Imports {
		switch {
		case imp.Alias != "" && len(imp.Symbols) == 0:
			g.linef(`%s %q`, imp.Alias, imp.Path)
		case len(imp.Symbols) > 0:
			g.linef(`%s %q`, genPkgAlias(imp), imp.Path)
		default:
			// Plain @import "path" — a normal Go import.
			g.linef(`%q`, imp.Path)
		}
	}
	g.line("")
	g.line(`"github.com/xDarkicex/nanite-gsx"`)
	g.line(`"github.com/xDarkicex/nanite-render"`)
	g.line(")")
	g.line("")

	// Props type alias (for destructured imports).
	if len(p.Imports) > 0 {
		for _, imp := range p.Imports {
			if len(imp.Symbols) > 0 {
				alias := genPkgAlias(imp)
				for _, sym := range imp.Symbols {
					g.linef("type %s = %s.%s", sym, alias, sym)
				}
			}
		}
	}

	// Multi-param components get a generated props struct so the
	// dynamic registration can BindProps the any payload.
	if len(p.Params) > 1 {
		g.line("")
		g.linef("type %sProps struct {", p.FuncName)
		g.indent++
		for _, param := range p.Params {
			fields := strings.Fields(param)
			if len(fields) < 2 {
				continue
			}
			// "user models.User" → Name "user", Type "models.User".
			name := fields[0]
			typ := fields[len(fields)-1]
			exported := strings.ToUpper(name[:1]) + name[1:]
			g.linef("%s %s `nanite:%q`", exported, typ, name)
		}
		g.indent--
		g.line("}")
		g.line("")
	}

		// The zero-byte marker type: `type X struct{}` exists solely so
	// cross-package `@import { X } from "..."` compiles as a Go
	// type alias (`type X = pkg.X`) even though the component is
	// actually the function `RenderX`. Costs zero bytes at runtime;
	// the symbol table resolves <X/> tags to pkg.RenderX.
	g.linef("type %s struct{}", p.FuncName)
	g.line("")

	// The strongly-typed render function. Children closure is always
	// the last param — callers pass nil when there are no children.
	params := append([]string{"c *render.ComponentContext"}, p.Params...)
	params = append(params, "children func(c *render.ComponentContext) error")
	returns := "error"
	g.line("")
	g.linef("func Render%s(%s) %s {", p.FuncName, strings.Join(params, ", "), returns)
	g.indent = 1

	// @css / @js — asset dependencies as the first lines.
	for _, href := range p.CSSAssets {
		g.linef("c.RequiresCSS(%q)", href)
	}
	for _, src := range p.JSAssets {
		g.linef("c.RequiresJS(%q)", src)
	}

	// Alpine x-cloak: if the component uses any x- or @ attribute,
	// inject the anti-flicker CSS rule so the UI is hidden until
	// Alpine initializes. Inline style, idempotent.
	if bodyUsesAlpine(p) {
		g.line(`c.WriteString(` + "`" + xCloakStyle + "`" + `)`)
	}

	// GSX_DEV_MODE: inject the live-reload script into layouts
	// (files with @yield) so the browser auto-refreshes on
	// recompile. One connection, one reload directive.
	if isDevMode() && bodyHasYield(p) {
		g.line(`c.WriteString(` + "`" + devReloadScript + "`" + `)`)
	}
}

// xCloakStyle hides Alpine-managed elements until Alpine loads.
const xCloakStyle = `<style>[x-cloak]{display:none!important}</style>`

// bodyUsesAlpine reports whether the body has any attribute
// starting with x- (Alpine data/bind/show) or @ (Alpine events) —
// the signal to inject x-cloak.
func bodyUsesAlpine(p *parser.ParsedFile) bool {
	s := p.Body
	for i := 0; i < s.Count; i++ {
		for k := int(s.AttrStart[i]); k < int(s.AttrEnd[i]); k++ {
			key := s.AttrKeys[k]
			if strings.HasPrefix(key, "x-") || strings.HasPrefix(key, "@") {
				return true
			}
		}
	}
	return false
}

// devReloadScript connects to the gsx watch SSE server and
// reloads the page when a message arrives.
const devReloadScript = `<script>new EventSource("http://localhost:3001/reload").onmessage=function(){location.reload()}</script>`

// isDevMode reports whether GSX_DEV_MODE is set.
func isDevMode() bool {
	_, ok := os.LookupEnv("GSX_DEV_MODE")
	return ok
}

// bodyHasYield reports whether the body contains a @yield node —
// the marker for a layout.
func bodyHasYield(p *parser.ParsedFile) bool {
	for i := 0; i < p.Body.Count; i++ {
		if p.Body.Kind[i] == ir.KindYield {
			return true
		}
	}
	return false
}

func (g *generator) emitFooter() {
	p := g.parsed
	g.indent = 0
	g.line("}")
	g.line("")

	// The registration wrapper (external dynamic path) — the
	// engine registration always exists so RenderNamed works.
	regName := "Register" + p.FuncName
	g.linef("func %s(e *gsx.Engine) {", regName)
	g.indent = 1
	g.linef(`e.Register(%q, func(c *render.ComponentContext, data any) error {`, p.FuncName)

	prelude, args := g.registrationArgs()
	for _, stmt := range prelude {
		g.line(stmt)
	}
	g.linef("return Render%s(c, %s)", p.FuncName, strings.Join(args, ", "))

	g.indent = 1
	g.line("})")
	g.indent = 0
	g.line("}")
	g.line("")

	// Decorator/action path: if any lifecycle decorator OR a
	// colocated action exists, also emit the component
	// registration via nanite-render's fluent builder — this
	// wires Suspense, OOB swaps, fallbacks, and server actions
	// into the ComponentRegistry so templates can dispatch
	// <UserProfile/> and inherit the lifecycles.
	if p.OOBID != "" || p.Async || len(p.Actions) > 0 || p.Memo.Param != "" {
		g.emitDecoratedRegistration()
	}
}

// emitDecoratedRegistration emits RegisterXComponent(cr) — the
// fluent builder chain for lifecycle decorators.
func (g *generator) emitDecoratedRegistration() {
	p := g.parsed
	g.linef("func Register%sComponent(cr *render.ComponentRegistry) {", p.FuncName)
	g.indent = 1

	// Build the chain: cr.Define("X").WithOOB(...).Async()...
	chain := fmt.Sprintf("cr.Define(%q)", p.FuncName)
	if p.OOBID != "" {
		chain += fmt.Sprintf(".WithOOB(%q)", p.OOBID)
	}
	if p.Async {
		chain += ".Async()"
	}
	if p.Fallback != "" {
		chain += fmt.Sprintf(".Fallback(func(c *render.ComponentContext) error { return Render%s(c, nil) })", p.Fallback)
	}
	// Colocated server actions — @action blocks hoisted into the
	// fluent builder chain.
	for _, a := range p.Actions {
		chain += fmt.Sprintf(".Action(%q, func(%s) error {\n%s\n\t\t})", a.Name, a.Sig, a.Body)
	}
	g.linef("%s.Render(func(c *render.ComponentContext) error {", chain)
	g.indent++
	// The Render closure receives c *ComponentContext — data is on c.Data.
	prelude, args := g.registrationArgs()
	// registrationArgs emits data.(Type); in the registry path the
	// data is c.Data.
	for i := range prelude {
		prelude[i] = strings.Replace(prelude[i], "data", "c.Data", 1)
	}
	for i := range args {
		args[i] = strings.Replace(args[i], "data.", "c.Data.", 1)
	}
	for _, stmt := range prelude {
		g.line(stmt)
	}
	g.linef("return Render%s(c, %s)", p.FuncName, strings.Join(args, ", "))
	g.indent--
	g.line("}).Register(cr)")

	// @memo — wrap the registered component with a memoization
	// cache. Memoize looks up the existing component and wraps it.
	if p.Memo.Param != "" {
		g.linef("cr.Memoize(%q, func(rc *render.RenderContext, data any) string {", p.FuncName)
		g.indent++
		g.linef("%s := data.(%s)", p.Memo.Param, p.Memo.Type)
		g.line(p.Memo.Body)
		g.indent--
		g.line("})")
	}
	g.indent = 0
	g.line("}")
}

func (g *generator) walk(start, end int) (int, error) {
	total := 0
	for i := start; i < end; i++ {
		consumed, err := g.emitNode(i)
		if err != nil {
			return 0, err
		}
		total += consumed
		i += consumed - 1
	}
	return total, nil
}

func (g *generator) emitNode(i int) (int, error) {
	s := g.parsed.Body

	switch s.Kind[i] {
	case ir.KindText:
		if t := s.Text[i]; t != "" {
			g.linef("c.WriteString(`%s`)", t)
		}

	case ir.KindExpr:
		g.linef("c.WriteString(html.EscapeString(fmt.Sprint(%s)))", s.Text[i])

	case ir.KindRawExpr:
		g.linef("c.WriteString(fmt.Sprint(%s))", s.Text[i])

	case ir.KindHTMLTag:
		g.emitOpenTag(i)
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		return consumed, nil

	case ir.KindHTMLClose:
		g.linef("c.WriteString(`</%s>`)", s.Tag[i])

	case ir.KindChildren:
		g.line("if children != nil { children(c) }")

	case ir.KindYield:
		g.line("if err := c.Yield(); err != nil { return err }")

	case ir.KindError:
		// @error("field") — the form error span boilerplate.
		field := s.Text[i]
		g.linef("if __err := c.Context.GetFormError(%q); __err != \"\" {", field)
		g.indent++
		g.line(`c.WriteString("<span class=\"error\">")`)
		g.line("c.WriteString(html.EscapeString(__err))")
		g.line(`c.WriteString("</span>")`)
		g.indent--
		g.line("}")

	case ir.KindFragment:
		// Fragments (<>...</>) emit no bytes — just walk children.
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		return consumed, nil

	case ir.KindComponent:
		return g.emitComponent(i)

	case ir.KindIf:
		return g.emitIf(i)

	case ir.KindFor:
		g.linef("for %s {", s.Cond[i])
		g.indent++
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		g.line("}")
		return consumed, nil

	case ir.KindSwitch:
		g.linef("switch %s {", s.Cond[i])
		g.indent++
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		g.line("}")
		return consumed, nil

	case ir.KindCase:
		g.linef("case %s:", s.Cond[i])
		g.indent++
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		return consumed, nil

	case ir.KindDefault:
		g.line("default:")
		g.indent++
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		return consumed, nil
	}
	return 1, nil
}

func (g *generator) emitIf(i int) (int, error) {
	s := g.parsed.Body
	g.linef("if %s {", s.Cond[i])
	g.indent++
	consumed := 1
	fc := int(s.FirstChild[i])
	if fc != -1 {
		n, err := g.walk(fc, g.siblingEnd(fc))
		if err != nil {
			return 0, err
		}
		consumed += n
	}
	g.indent--
	ns := int(s.NextSibling[i])
	if ns != -1 && s.Kind[ns] == ir.KindElse {
		g.line("} else {")
		g.indent++
		efc := int(s.FirstChild[ns])
		if efc != -1 {
			n, err := g.walk(efc, g.siblingEnd(efc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		consumed++
	}
	g.line("}")
	return consumed, nil
}

// registrationArgs builds the argument list for the engine
// registration wrapper. The render signature is
// (c, p1..pN, children) — so N params produce N+1 args.
//
// Single param: data.(Type) — direct assertion, zero cost.
// Multi param: BindProps[GeneratedProps](data) — the generated
// props struct bridges the any payload to the typed params.
// Zero params: just the nil children closure.
//
// Returns (prelude, args) — prelude are statements emitted
// before the call (the props binding for multi-param).
func (g *generator) registrationArgs() (prelude, args []string) {
	p := g.parsed
	switch {
	case len(p.Params) > 1:
		// BindProps path — the generated XProps struct.
		prelude = append(prelude, fmt.Sprintf("props := render.BindProps[%sProps](data)", p.FuncName))
		for _, param := range p.Params {
			fields := strings.Fields(param)
			if len(fields) < 2 {
				continue
			}
			name := fields[0]
			exported := strings.ToUpper(name[:1]) + name[1:]
			args = append(args, fmt.Sprintf("props.%s", exported))
		}
	case len(p.Params) == 1:
		fields := strings.Fields(p.Params[0])
		if len(fields) > 0 {
			typ := fields[len(fields)-1]
			args = append(args, fmt.Sprintf("data.(%s)", typ))
		}
	}
	args = append(args, "nil") // children closure
	return prelude, args
}

func (g *generator) emitOpenTag(i int) {
	s := g.parsed.Body
	tag := s.Tag[i]
	start := int(s.AttrStart[i])
	end := int(s.AttrEnd[i])
	if start == end {
		g.linef("c.WriteString(`<%s>`)", tag)
		return
	}

	// Split attrs into static runs, dynamic expressions, and
	// spreads.
	g.linef("c.WriteString(`<%s`)", tag)
	for k := start; k < end; k++ {
		key := s.AttrKeys[k]
		val := s.AttrVals[k]
		switch {
		case k < len(s.AttrHydrate) && s.AttrHydrate[k]:
			// @hydrate("x-data", state) → WriteHydrateProps.
			parts := strings.SplitN(val, "\x00", 2)
			if len(parts) == 2 {
				g.linef("c.WriteHydrateProps(%q, %s)", parts[0], parts[1])
			}
		case k < len(s.AttrSpread) && s.AttrSpread[k]:
			// {...attrs} — spread a map[string]string at runtime.
			g.linef("for __k, __v := range %s {", val)
			g.indent++
			g.line(`c.WriteString(" ")`)
			g.line("c.WriteString(html.EscapeString(fmt.Sprint(__k)))")
			g.line(`c.WriteString("=\"")`)
			g.line("c.WriteString(html.EscapeString(fmt.Sprint(__v)))")
			g.line(`c.WriteString("\"")`)
			g.indent--
			g.line("}")
		case k < len(s.AttrDynamic) && s.AttrDynamic[k]:
			// Alpine x-data / x-init with a Go expression:
			// auto-convert to the JSON hydration bridge —
			// fmt.Sprint of a Go map is NOT valid Alpine JS.
			if key == "x-data" || key == "x-init" {
				g.linef("c.WriteHydrateProps(%q, %s)", key, val)
				continue
			}
			g.linef(`c.WriteString(" %s=\"")`, key)
			g.linef("c.WriteString(html.EscapeString(fmt.Sprint(%s)))", val)
			g.linef(`c.WriteString("\"")`)
		default:
			// Static attribute values may contain double quotes
			// (e.g. placeholder='["ops"]') — escape them for the
			// emitted Go string literal.
			g.linef(`c.WriteString(" %s=\"%s\"")`, key, goStr(val))
		}
	}
	g.line(`c.WriteString(">")`)
}

func (g *generator) emitComponent(i int) (int, error) {
	s := g.parsed.Body
	name := s.Tag[i]
	start := int(s.AttrStart[i])
	end := int(s.AttrEnd[i])

	// Resolve the render function: same-package components are
	// local (RenderName); destructured-imported components are
	// qualified (ui.RenderName) via the symbol table — the
	// TSX-style cross-package composition mechanism.
	fn := "Render" + name
	if alias, ok := g.symbols[name]; ok {
		fn = alias + "." + fn
	}

	// Collect positional args from attributes.
	var args []string
	for k := start; k < end; k++ {
		args = append(args, g.genCompArg(k, s.AttrVals[k]))
	}

	// Children: if this component was opened (not self-closing),
	// walk its children and wrap in a closure.
	consumed := 1
	fc := int(s.FirstChild[i])
	if fc != -1 {
		childEnd := g.siblingEnd(fc)
		g.linef("if err := %s(c, %s, func(c *render.ComponentContext) error {", fn, strings.Join(args, ", "))
		g.indent++
		if _, err := g.walk(fc, childEnd); err != nil {
			return 0, err
		}
		consumed += childEnd - fc
		g.indent--
		g.line("}); err != nil { return err }")
		return consumed, nil
	}

	// No children — self-closing component.
	args = append(args, "nil")
	call := fmt.Sprintf("if err := %s(c", fn)
	if len(args) > 0 {
		call += ", " + strings.Join(args, ", ")
	}
	call += "); err != nil { return err }"
	g.line(call)
	return consumed, nil
}

func genPkgAlias(imp parser.Import) string {
	if imp.Alias != "" {
		return imp.Alias
	}
	// Generate alias from path: "myapp/models" -> "models"
	path := imp.Path
	if idx := strings.LastIndexByte(path, '/'); idx >= 0 {
		return path[idx+1:]
	}
	return path
}

// genCompArg formats a component attribute as a Go function argument.
// Keys are ignored in positional-style — all values are passed positionally.
func (g *generator) genCompArg(k int, val string) string {
	// Dynamic attrs ({expr}) pass the Go expression raw; static
	// attrs ("str") are string literals — quote them.
	if k < len(g.parsed.Body.AttrDynamic) && g.parsed.Body.AttrDynamic[k] {
		return val
	}
	return fmt.Sprintf("%q", val)
}

func (g *generator) siblingEnd(start int) int {
	s := g.parsed.Body
	cur := start
	for s.NextSibling[cur] != -1 {
		cur = int(s.NextSibling[cur])
	}
	return cur + 1
}

func (g *generator) line(s string) {
	for j := 0; j < g.indent; j++ {
		g.buf.WriteByte('\t')
	}
	g.buf.WriteString(s)
	g.buf.WriteByte('\n')
}

func (g *generator) linef(format string, args ...any) {
	g.line(fmt.Sprintf(format, args...))
}
