// Package codegen generates Go source code from the gsx
// intermediate representation.
package codegen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/xDarkicex/nanite-gsx/internal/ir"
)

// Standalone generates a pure Go function that writes to
// io.Writer with zero external dependencies. The function
// signature mirrors the @view declaration.
func Standalone(stream ir.NodeStream) (string, error) {
	g := &generator{buf: new(bytes.Buffer), stream: stream}
	g.emitPreamble()
	if _, err := g.walk(0, stream.Count); err != nil {
		return "", err
	}
	g.emitPostamble()
	return g.buf.String(), nil
}

type generator struct {
	buf    *bytes.Buffer
	stream ir.NodeStream
	indent int
}

func (g *generator) emitPreamble() {
	g.line("// Code generated by nanite-gsx. DO NOT EDIT.")
	g.line("")
	g.line("package views")
	g.line("")
	g.line("import (")
	g.line(`"fmt"`)
	g.line(`"html"`)
	g.line(`"io"`)
	g.line(")")
	g.line("")

	params := strings.Join(g.stream.ViewProps, ", ")
	returns := strings.Join(g.stream.ViewReturns, ", ")
	g.linef("func Render%s(w io.Writer, %s) (%s) {", g.stream.ViewName, params, returns)
	g.indent = 1
}

func (g *generator) emitPostamble() {
	if len(g.stream.ViewReturns) > 0 {
		g.line("return nil")
	}
	g.indent = 0
	g.line("}")
}

// walk processes nodes [start, end) and returns the total number
// of nodes consumed. Callers use this to propagate subtree sizes
// up through nested containers (if → span → children).
func (g *generator) walk(start, end int) (int, error) {
	total := 0
	for i := start; i < end; i++ {
		consumed, err := g.emitNode(i)
		if err != nil {
			return 0, err
		}
		total += consumed
		i += consumed - 1 // -1 because the for loop does i++
	}
	return total, nil
}

// emitNode writes one node and returns how many contiguous
// sibling indices were consumed (1 for simple nodes; >1 for
// control-flow nodes whose children were walked inline).
func (g *generator) emitNode(i int) (int, error) {
	s := g.stream
	k := s.Kind[i]

	switch k {
	case ir.KindText:
		if t := s.Text[i]; t != "" {
			g.linef("w.Write([]byte(`%s`))", t)
		}

	case ir.KindExpr:
		g.linef("io.WriteString(w, html.EscapeString(fmt.Sprint(%s)))", s.Text[i])

	case ir.KindRawExpr:
		g.linef("io.WriteString(w, fmt.Sprint(%s))", s.Text[i])

	case ir.KindHTMLTag:
		g.emitOpenTag(i)
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			end := g.siblingEnd(fc)
			n, err := g.walk(fc, end)
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		return consumed, nil

	case ir.KindHTMLClose:
		g.linef("w.Write([]byte(`</%s>`))", s.Tag[i])

	case ir.KindComponent:
		g.emitComponent(i)

	case ir.KindIf:
		return g.emitIf(i)

	case ir.KindElse:
		// Handled by KindIf — silently skip here (main walk hits
		// it after the if consumed it).

	case ir.KindFor:
		g.linef("for %s {", s.Cond[i])
		g.indent++
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		g.line("}")
		return consumed, nil

	case ir.KindSwitch:
		g.linef("switch %s {", s.Cond[i])
		g.indent++
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		g.line("}")
		return consumed, nil

	case ir.KindCase:
		g.linef("case %s:", s.Cond[i])
		g.indent++
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		return consumed, nil

	case ir.KindDefault:
		g.line("default:")
		g.indent++
		consumed := 1
		fc := int(s.FirstChild[i])
		if fc != -1 {
			n, err := g.walk(fc, g.siblingEnd(fc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		return consumed, nil
	}
	return 1, nil
}

func (g *generator) emitIf(i int) (int, error) {
	s := g.stream
	g.linef("if %s {", s.Cond[i])
	g.indent++
	consumed := 1
	fc := int(s.FirstChild[i])
	if fc != -1 {
		n, err := g.walk(fc, g.siblingEnd(fc))
		if err != nil {
			return 0, err
		}
		consumed += n
	}
	g.indent--
	// Handle @else sibling.
	ns := int(s.NextSibling[i])
	if ns != -1 && s.Kind[ns] == ir.KindElse {
		g.line("} else {")
		g.indent++
		efc := int(s.FirstChild[ns])
		if efc != -1 {
			n, err := g.walk(efc, g.siblingEnd(efc))
			if err != nil {
				return 0, err
			}
			consumed += n
		}
		g.indent--
		consumed++ // the @else node itself
	}
	g.line("}")
	return consumed, nil
}

func (g *generator) emitOpenTag(i int) {
	tag := g.stream.Tag[i]
	start := int(g.stream.AttrStart[i])
	end := int(g.stream.AttrEnd[i])
	if start == end {
		g.linef("w.Write([]byte(`<%s>`))", tag)
		return
	}
	var parts []string
	parts = append(parts, fmt.Sprintf("<%s", tag))
	for k := start; k < end; k++ {
		parts = append(parts, fmt.Sprintf(` %s="%s"`, g.stream.AttrKeys[k], g.stream.AttrVals[k]))
	}
	parts = append(parts, ">")
	g.linef("w.Write([]byte(`%s`))", strings.Join(parts, ""))
}

func (g *generator) emitComponent(i int) {
	name := g.stream.Tag[i]
	start := int(g.stream.AttrStart[i])
	end := int(g.stream.AttrEnd[i])
	var args []string
	for k := start; k < end; k++ {
		args = append(args, fmt.Sprintf("%s: %s", g.stream.AttrKeys[k], g.stream.AttrVals[k]))
	}
	call := fmt.Sprintf("Render%s(w", name)
	if len(args) > 0 {
		call += ", " + strings.Join(args, ", ")
	}
	call += ")"
	g.line(call)
}

func (g *generator) siblingEnd(start int) int {
	cur := start
	for g.stream.NextSibling[cur] != -1 {
		cur = int(g.stream.NextSibling[cur])
	}
	return cur + 1
}

func (g *generator) line(s string) {
	for j := 0; j < g.indent; j++ {
		g.buf.WriteByte('\t')
	}
	g.buf.WriteString(s)
	g.buf.WriteByte('\n')
}

func (g *generator) linef(format string, args ...any) {
	g.line(fmt.Sprintf(format, args...))
}
